# Generated by Django 5.2.3 on 2025-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En mantenimiento'), ('fuera', 'Fuera de servicio')], max_length=50)),
            ],
        ),
    ]
